### PR TITLE
Container image

### PR DESCRIPTION
**Pull request by glatard**
This PR adds a Dockerfile and scripts to build a Singularity image that supports regular and fuzzy fmriprep executions. It also adds a child dataset under `envs`, containing the Singularity image stored on OSF. See `envs/README.md` for more information.

The OSF dataset (https://osf.io/rbu92) storing the Singularity image can't be made public now because it was marked as spam by OSF so you will have to export OSF_TOKEN before you can `datalad get` the Singularity image. I'm in touch with OSF support, this issue should be resolved in the coming hours. In the meantime I can DM a token if needed.

Do we want `envs/singularity-images` to remain a child dataset? If so, you might want to copy https://github.com/glatard/fmriprep-lts-images to the SIMEXP org and update `.gitmodules` accordingly.

### CODE REVIEW

**Review by ltetrel — COMMENTED** [review]
`.gitignore`
What do you want to filter with that file ?

**Review by ltetrel — COMMENTED** [review]
`envs/Dockerfile`
I would add 2 separate images: one without mca at all, and the second with it.
This has I think two advantages:
1. If the user choose to run without mca, he is sure that this is the environment he would indeed use when running his preprocessing.
2. Avoid the ENTRYPOINT which impact somehow the image containerization (creates a dependency path on the host).

**Comment by glatard** [comment]
> `.gitignore`
> What do you want to filter with that file ?

Tilde (`~`) files, they're temp files in emacs and other editors.

**Review by ltetrel — COMMENTED** [review]
`envs/Dockerfile` `envs/README.md` `envs/build.sh`
If we want to be compliant with YODA, all code should live inside the `code` folder

**Comment by glatard** [comment]
> `envs/Dockerfile`
> I would add 2 separate images: one without mca at all, and the second with it.
> This has I think two advantages:
> 
>     1. If the user choose to run without mca, he is sure that this is the environment he would indeed use when running his preprocessing.
> 
>     2. Avoid the ENTRYPOINT which impact somehow the image containerization (creates a dependency path on the host).

Sure, we can do that but it would also create a nearly identical image and double the storage space / transfer time if both are needed. There's no way the fuzzy environment is triggered unless `/opt/mca-libmath/libmath.so'` is preloaded, which is only done if variable `FUZZY` is set.

**Review by ltetrel — COMMENTED** [review]
`requirements.txt`
is datalad-osf dependency used just to push and update the datalad repo ?
Or it also needs to be installed if you want to clone the lts-repo (and the sing images) ?

**Comment by ltetrel** [comment]
> > `envs/Dockerfile`
> > I would add 2 separate images: one without mca at all, and the second with it.
> > This has I think two advantages:
> > ```
> > 1. If the user choose to run without mca, he is sure that this is the environment he would indeed use when running his preprocessing.
> > 
> > 2. Avoid the ENTRYPOINT which impact somehow the image containerization (creates a dependency path on the host).
> > ```
> 
> Sure, we can do that but it would also create a nearly identical image and double the storage space / transfer time if both are needed. There's no way the fuzzy environment is triggered unless `/opt/mca-libmath/libmath.so'` is preloaded, which is only done if variable `FUZZY` is set.

Yes I imagine you did the necessary to not load it :) But I would still go for two separate images just because the environment is not the same (even if not loaded), just in case.

**Comment by glatard** [comment]
> `requirements.txt`
> is datalad-osf dependency used just to push and update the datalad repo ?
> Or it also needs to be installed if you want to clone the lts-repo (and the sing images) ?

idk for sure, will check and get back to you.

**Comment by ltetrel** [comment]
> > `requirements.txt`
> > is datalad-osf dependency used just to push and update the datalad repo ?
> > Or it also needs to be installed if you want to clone the lts-repo (and the sing images) ?
> 
> idk for sure, will check and get back to you.

Anayway this does not change the fact that it should be included anyway, it is just for my knowledge :P

**Review by ltetrel — COMMENTED** [review]
`envs/build.sh` ` envs/README.md`
Are we able to get a specific version from fmriprep with your current solution ?
You made it so the version can be changed when building (and pushing) to OSF, but I am not sure what would be the best method to get specific version from OSF.
Overall a generic question regarding LTS support, do we plan to support a single fmriprep version for multiple years (in that case, your current solution is ok), or multiple fmriprep versions ? (@pbellec @bpinsard )

**Comment by glatard** [comment]
> `envs/build.sh` ` envs/README.md`
> Are we able to get a specific version from fmriprep with your current solution ?
> You made it so the version can be changed when building (and pushing) to OSF, but I am not sure what would be the best method to get specific version from OSF.
> Overall a generic question regarding LTS support, do we plan to support a single fmriprep version for multiple years (in that case, your current solution is ok), or multiple fmriprep versions ? (@pbellec @bpinsard )

With datalad we should be able to get back to a specific version if we tag versions of this repo properly.

**Comment by ltetrel** [comment]
> > `envs/build.sh` ` envs/README.md`
> > Are we able to get a specific version from fmriprep with your current solution ?
> > You made it so the version can be changed when building (and pushing) to OSF, but I am not sure what would be the best method to get specific version from OSF.
> > Overall a generic question regarding LTS support, do we plan to support a single fmriprep version for multiple years (in that case, your current solution is ok), or multiple fmriprep versions ? (@pbellec @bpinsard )
> 
> With datalad we should be able to get back to a specific version if we tag versions of this repo properly.

Indeed, but maybe we would like to get all up-to-date changes, and just changing the fmriprep version ? I am not aware of all datalad capabilities so I may actually be wrong..

**Comment by glatard** [comment]
Hi @ltetrel, I updated this PR as follows:
* Now build two images instead of one
* Moved all code to `code/containers`
Let me know if anything else should be updated!

**Comment by glatard** [comment]
P.S.: the OSF dataset is now public so you should be able to datalad get the image files without an OSF token.

**Comment by ltetrel** [comment]
> Hi @ltetrel, I updated this PR as follows:
> 
>     * Now build two images instead of one
> 
>     * Moved all code to `code/containers`
>       Let me know if anything else should be updated!

Great, I will test it as soon as possible, thank you!

**Comment by ltetrel** [comment]
Alright I published a new branch `CONTAINER` which fixes some remaining issues, would you be able to update this PR with my changes if they look good to you ? (not able to modify this PR).
https://github.com/SIMEXP/fmriprep-lts/commit/440d6e89ac7be85f891b10797b7375f8cd68c378
https://github.com/SIMEXP/fmriprep-lts/commit/1184b2d2cee9d3eb063dd31404e6e595cb33fc04
I also tested the `datalad get`, and `docker build` and all seems to work well.

**Comment by glatard** [comment]
I added a few comments to the commits, let me know what you think. About the renaming of `code/containers` to `code/docker`, it might be a bit ambiguous since `build.sh` builds Singularity images eventually.

**Comment by ltetrel** [comment]
> I added a few comments to the commits, let me know what you think. About the renaming of `code/containers` to `code/docker`, it might be a bit ambiguous since `build.sh` builds Singularity images eventually.

I reverted back the old naming https://github.com/SIMEXP/fmriprep-lts/commit/b5119e1ee33b50b98fa910857532cb35dae6b9aa
If everything looks good to you @glatard I will merge your PR and add my changes.
Or you can update this PR also (maybe this is cleaner).

**Pull request merged**
